name = "dinner-helper-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[rules]]
type = "Text"
globs = ["**/*.md"]
fallthrough = true

[[d1_databases]]
binding = "DB"
database_name = "dinnerhelper-db"
database_id = "d70d94aa-6d62-43ad-9817-c163478d3fd0"
migrations_dir = "../migrations"
